Repository filetrust/cdr-plugin-folder-to-folder, pull requests merged in 2021-05, with the labels that each got.

#249 Server statuses updated every second on long lasting pre and processing operations
  cdr_plugin_folder_to_folder/api/Server.py
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
  cdr_plugin_folder_to_folder/pre_processing/Status.py
  cdr_plugin_folder_to_folder/processing/Loops.py
  tests/integration/configure/test_Configure_Env.py
  tests/integration/processing/test_File_Processing.py
  tests/unit/api/test_Server.py
  tests/unit/pre_processing/test_Status.py
  tests/unit/processing/test_Loops.py
Labels: ready-for-review

#276 Utilize /api/analyse/rebuild-zip-from-base64 API from recent GW SDK (issue 220)
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/processing/File_Processing.py
  cdr_plugin_folder_to_folder/processing/Loops.py
  tests/integration/configure/test_Configure_Env.py
  tests/integration/processing/test_File_Processing.py
Labels: ready-for-review

#318 Initial implementation of the endpoints service (issue 151, 153)
  .github/workflows/auto_tagging.yml
  .github/workflows/gh-pages.yml
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/configure/Configure_Env.py
  cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
  cdr_plugin_folder_to_folder/processing/Endpoint_Service.py
  cdr_plugin_folder_to_folder/processing/File_Processing.py
  cdr_plugin_folder_to_folder/processing/Loops.py
  cdr_plugin_folder_to_folder/storage/Storage.py
  infra/packer/ova-check.sh
  tests/integration/configure/test_Configure_Env.py
  tests/integration/processing/test_File_Processing.py
  tests/unit/api/routes/test_File_Distributor.py
  tests/unit/configure/test_Configure_Env_core.py
  tests/unit/processing/test_Endpoint_Service.py
  tests/unit/processing/test_Loops.py
Labels: ready-for-review

#330 Download ZIP files from url (issue 194)
  cdr_plugin_folder_to_folder/api/routes/Pre_Processor.py
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
  tests/unit/api/test_Server.py
  tests/unit/pre_processing/test_Pre_Processor.py
Labels: ready-for-review

#341 Mark all hd2 files unprocessed, reset the status of files on retry (issues 228, 239)
  cdr_plugin_folder_to_folder/api/routes/Pre_Processor.py
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/metadata/Metadata_Service.py
  cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
  cdr_plugin_folder_to_folder/pre_processing/Status.py
  cdr_plugin_folder_to_folder/processing/File_Processing.py
  cdr_plugin_folder_to_folder/processing/Loops.py
  tests/unit/api/test_Server.py
Labels: ready-for-review

#319 Modified documentation and added new dashboard
  cdr_plugin_folder_to_folder/metadata/Metadata_Elastic.py
  diagrams/OVAsFlow.drawio
  diagrams/arrows.drawio
  diagrams/newCDRFlow.drawio
  website/content/_index.md
  website/content/docs/0. Introduction.md
  website/content/docs/4. End to end workflow ESXI copy.md
  website/content/docs/5. End to end workflow AWS.md
  website/content/docs/6. How to start.md
  website/content/docs/7. FAQ.md
  website/content/docs/page-1.md
  website/content/docs/remote_storage_mount.md
Labels: Needs fix, ready-for-review

#304 Ova esxi documentation
  infra/terraform/esxi/README.md
Labels: Needs fix

#346 White list of extensions (issue 342)
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/configure/Configure_Env.py
  cdr_plugin_folder_to_folder/metadata/Metadata.py
  cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
  cdr_plugin_folder_to_folder/pre_processing/Status.py
  cdr_plugin_folder_to_folder/processing/File_Processing.py
  cdr_plugin_folder_to_folder/processing/Loops.py
  cdr_plugin_folder_to_folder/storage/Storage.py
  tests/integration/processing/test_File_Processing.py
  tests/unit/api/routes/test_Configure.py
  tests/unit/common_settings/test_Config.py
  tests/unit/pre_processing/test_Status.py
  tests/unit/processing/test_Loops.py
Labels: ready-for-review

#411 Added support of React and changed Server Config page to React
  .gitignore
  website/site/assets/js/HighlightTexts.jsx
  website/site/layouts/_default/single.html
  website/site/layouts/shortcodes/status/server_config.html
  website/site/package-lock.json
  website/site/package.json
Labels: ready-for-review

#399 Change "Completed OK" and "Completed with Errors" (issue 353)
  cdr_plugin_folder_to_folder/metadata/Metadata.py
  cdr_plugin_folder_to_folder/pre_processing/Status.py
  cdr_plugin_folder_to_folder/processing/Endpoint_Service.py
  cdr_plugin_folder_to_folder/processing/File_Processing.py
  cdr_plugin_folder_to_folder/processing/Loops.py
  tests/unit/pre_processing/test_Status.py
  tests/unit/processing/test_Endpoint_Service.py
  tests/unit/processing/test_Loops.py
Labels: ready-for-review

#421 Fix Website to load urls from data file instead of hardcoded url
  .github/workflows/run-tests.yml
  .gitignore
  bin/website-docker-build-run.sh
  website/Dockerfile
  website/site/layouts/shortcodes/status/processing_status.html
  website/site/layouts/shortcodes/status/server_config.html
  website/site/package-lock.json
Labels: P0, bug, ready-for-review

#432 Fix pytest warnings (issue 305)
  cdr_plugin_folder_to_folder/api/routes/Pre_Processor.py
  cdr_plugin_folder_to_folder/api/routes/Processing.py
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
  cdr_plugin_folder_to_folder/pre_processing/Status.py
  cdr_plugin_folder_to_folder/utils/testing/Test_Data.py
  tests/integration/processing/test_File_Processing.py
  tests/unit/api/routes/test_File_Distributor.py
  tests/unit/api/test_Server.py
  tests/unit/api/test_Server_Status.py
  tests/unit/file_distribution/test_File_Distributor_core.py
  tests/unit/pre_processing/test_Pre_Processor.py
  tests/unit/pre_processing/test_Prometheus_Status_Metrics.py
  tests/unit/pre_processing/test_Status.py
  tests/unit/processing/test_Loops.py
  tests/unit/processing/test_Processor.py
Labels: ready-for-review

#455 Update cdr-plugin.yml to use correct secret for AMI/OVA
  .github/workflows/cdr-plugin.yml
Labels: ready-for-review
