Repository filetrust/cdr-plugin-folder-to-folder, pull requests merged in 2021-06, with the labels that each got.

#453 Update auto_tagging.yml
  .github/workflows/auto_tagging.yml
Labels: need-more-info

#461 Update auto_tagging.yml
  .github/workflows/auto_tagging.yml
Labels: ready-for-review

#468 Adding new workflows to docs
  website/content/docs/9. Additional workflows.md
  website/content/docs/remote_storage_mount.md
Labels: ready-for-review

#465 fixed /version api bug
  cdr_plugin_folder_to_folder/common_settings/Config.py
  docker-compose.yaml
  infra/packer/setup/setup.sh
  tests/integration/processing/test_File_Processing.py
Labels: ready-for-review

#484 Update test_File_Processing.py
  tests/integration/processing/test_File_Processing.py
Labels: ready-for-review

#482 For Release
  .github/workflows/auto_tagging.yml
  .github/workflows/codeql-analysis.yml
  cdr_plugin_folder_to_folder/common_settings/Config.py
  docker-compose.yaml
  infra/packer/setup/setup.sh
  tests/integration/processing/test_File_Processing.py
  website/content/docs/9. Additional workflows.md
  website/content/docs/remote_storage_mount.md
Labels: ready-for-review

#487 Documentation update
  website/content/docs/0. Introduction.md
  website/content/docs/1. How to deploy CDR Plugin AWS.md
  website/content/docs/1. How to deploy CDR Plugin OVA (workflow cluster).md
  website/content/docs/2. How to deploy CDR Plugin ESXI.md
  website/content/docs/3. End to end workflow AWS.md
  website/content/docs/3. How to deploy GW Cloud SDK (worker cluster).md
  website/content/docs/4. End to end workflow ESXI.md
  website/content/docs/4. How to deploy GW Desktop (UI VM) in ESXi.md
  website/content/docs/5. FAQ.md
  website/content/docs/6. How to start.md
  website/content/docs/7. Additional workflows.md
  website/content/docs/remote_storage_mount.md
Labels: ready-for-review

#494 Update setup.sh
  infra/packer/setup/setup.sh
Labels: ready-for-review

#490 Issue 52
  jupyter/notebooks/Set_Cloud_SDK_IPs.ipynb
Labels: ready-for-review

#503 Revert the changes for v0.10.3
  jupyter/notebooks/Set_Cloud_SDK_IPs.ipynb
Labels: P0, ready-for-review

#517 Docker compose extends
  .github/workflows/cdr-plugin.yml
  docker-compose.yaml
  infra/docker-compose/prometheus/CODE_OF_CONDUCT.md
  infra/docker-compose/prometheus/CONTRIBUTING.md
  infra/docker-compose/prometheus/Grafana Dashboard With Service.json
  infra/docker-compose/prometheus/Grafana_Dashboard.json
  infra/docker-compose/prometheus/HighLoadDashboard.json
  infra/docker-compose/prometheus/ISSUE_TEMPLATE.md
  infra/docker-compose/prometheus/LICENSE
  infra/docker-compose/prometheus/README.md
  infra/docker-compose/prometheus/alertmanager/config.yml
  infra/docker-compose/prometheus/dashboards/Grafana_Dashboard.json
  infra/docker-compose/prometheus/dashboards/Grafana_Dashboard_prom_2.json
  infra/docker-compose/prometheus/dashboards/System_Monitoring.json
  infra/docker-compose/prometheus/docker-compose.yml
  infra/docker-compose/prometheus/docker-prometheus.dockerapp/docker-compose.yml
  infra/docker-compose/prometheus/docker-stack.yml
  infra/docker-compose/prometheus/docker-traefik-stack.yml
  infra/docker-compose/prometheus/grafana/config.monitoring
  infra/docker-compose/prometheus/grafana/provisioning/dashboards/Docker Prometheus Monitoring-1571332751387.json
  infra/docker-compose/prometheus/grafana/provisioning/dashboards/dashboard.yml
  infra/docker-compose/prometheus/grafana/provisioning/datasources/datasource.yml
  infra/docker-compose/prometheus/images/Add_Data_Source.png
  infra/docker-compose/prometheus/images/Dashboard.png
  infra/docker-compose/prometheus/images/Import_Dashboard.png
  infra/docker-compose/prometheus/images/mac-filesystem.png
  infra/docker-compose/prometheus/mino-compose.yml
  infra/docker-compose/prometheus/prometheus/alert.rules
  infra/docker-compose/prometheus/prometheus/prometheus.yml
  infra/docker-compose/prometheus/promethgrafana-compose.yml
  infra/docker-compose/prometheus/pwd-stack.yml
  infra/packer/aws-ami-extends.json
  infra/packer/setup/docker-compose-extends.sh
  infra/packer/setup/setup.sh
Labels: ready-for-merge

#492 Moved Workflows to React version and fixed bugs
  .gitignore
  README.md
  website/content/workflows/_index.md
  website/content/workflows/f2f-workflows.md
  website/content/workflows/set-ip.md
  website/site/assets/js/Workflows.jsx
  website/site/assets/js/components/Loader/Loader.jsx
  website/site/assets/js/components/Loader/LoaderBlocking.jsx
  website/site/assets/js/components/Modal/GWDialog.jsx
  website/site/assets/js/components/WebIFrame/WebIFrame.jsx
  website/site/assets/js/components/buttons/GWButton.jsx
  website/site/assets/js/services/Services.jsx
  website/site/assets/js/services/Utils.jsx
  website/site/assets/js/style.css
  website/site/assets/js/workflows/Configuration.jsx
  website/site/assets/js/workflows/Dashboard.jsx
  website/site/assets/js/workflows/Processing.jsx
  website/site/assets/js/workflows/Workflow.jsx
  website/site/assets/jsconfig.json
  website/site/layouts/shortcodes/workflows/workflow.html
  website/site/package.json
  website/site/static/images/checked.png
  website/site/static/images/fire.png
  website/site/static/images/refresh.png
  website/site/static/images/spinner.png
Labels: Needs fix, P1, ready-for-merge, ready-for-review

#525 Fixed Bugs
  website/site/assets/js/services/Services.jsx
  website/site/assets/js/services/Utils.jsx
  website/site/assets/js/style.css
  website/site/assets/js/workflows/Configuration.jsx
  website/site/assets/js/workflows/Processing.jsx
  website/site/assets/js/workflows/Workflow.jsx
  website/site/package.json
Labels: P1, UI, ready-for-review

#533 Reverted PRs due to P0 issue
  .gitignore
  README.md
  website/content/workflows/_index.md
  website/content/workflows/f2f-workflows.md
  website/content/workflows/set-ip.md
  website/site/assets/js/Workflows.jsx
  website/site/assets/js/components/Loader/Loader.jsx
  website/site/assets/js/components/Loader/LoaderBlocking.jsx
  website/site/assets/js/components/Modal/GWDialog.jsx
  website/site/assets/js/components/WebIFrame/WebIFrame.jsx
  website/site/assets/js/components/buttons/GWButton.jsx
  website/site/assets/js/services/Services.jsx
  website/site/assets/js/services/Utils.jsx
  website/site/assets/js/style.css
  website/site/assets/js/workflows/Configuration.jsx
  website/site/assets/js/workflows/Dashboard.jsx
  website/site/assets/js/workflows/Processing.jsx
  website/site/assets/js/workflows/Workflow.jsx
  website/site/assets/jsconfig.json
  website/site/layouts/shortcodes/workflows/workflow.html
  website/site/package.json
  website/site/static/images/checked.png
  website/site/static/images/fire.png
  website/site/static/images/refresh.png
  website/site/static/images/spinner.png
Labels: ready-for-review

#497 Pre-process twice - issue 58
  cdr_plugin_folder_to_folder/api/routes/Pre_Processor.py
  cdr_plugin_folder_to_folder/metadata/Metadata.py
  cdr_plugin_folder_to_folder/pre_processing/Pre_Processor.py
  cdr_plugin_folder_to_folder/pre_processing/Status.py
  cdr_plugin_folder_to_folder/processing/Loops.py
  cdr_plugin_folder_to_folder/utils/testing/Temp_Config.py
  diagrams/cdr-plugin-folder-to-folder-pre-processing.drawio
  diagrams/cdr-plugin-folder-to-folder-pre-processing.png
  tests/integration/pre-processing/test_Pre_Processor_API_functions.py
  tests/integration/processing/test_File_Processing.py
  tests/unit/api/test_Server.py
  tests/unit/pre_processing/test_Pre_Processor.py
  tests/unit/pre_processing/test_Status.py
  tests/unit/processing/test_Processor.py
Labels: P0, ready-for-merge

#481 Updated metadata fields - issue 474
  cdr_plugin_folder_to_folder/configure/Configure_Env.py
  cdr_plugin_folder_to_folder/metadata/Metadata.py
  cdr_plugin_folder_to_folder/metadata/Metadata_Service.py
  cdr_plugin_folder_to_folder/processing/File_Processing.py
  tests/integration/processing/test_File_Processing.py
  tests/unit/metadata/test_Metadata_Service.py
  tests/unit/storage/test_Storage.py
Labels: P1, ready-for-merge

#541 Workflows UI changes, integrated new APIs, auto populate scenarios
  website/content/workflows/_index.md
  website/content/workflows/f2f-workflows.md
  website/content/workflows/set-ip.md
  website/site/assets/js/Workflows.jsx
  website/site/assets/js/components/EditableTable/EditableTable.jsx
  website/site/assets/js/components/Loader/Loader.jsx
  website/site/assets/js/components/Loader/LoaderBlocking.jsx
  website/site/assets/js/components/Modal/GWDialog.jsx
  website/site/assets/js/components/Table/GWTable.jsx
  website/site/assets/js/components/WebIFrame/WebIFrame.jsx
  website/site/assets/js/components/buttons/GWButton.jsx
  website/site/assets/js/services/Services.jsx
  website/site/assets/js/services/Utils.jsx
  website/site/assets/js/style.css
  website/site/assets/js/workflows/Configuration.jsx
  website/site/assets/js/workflows/Configuration/Components/CloudSDK.jsx
  website/site/assets/js/workflows/Configuration/Components/Others.jsx
  website/site/assets/js/workflows/Configuration/Components/Scenerios.jsx
  website/site/assets/js/workflows/Configuration/Configuration.jsx
  website/site/assets/js/workflows/Dashboard.jsx
  website/site/assets/js/workflows/Processing.jsx
  website/site/assets/jsconfig.json
  website/site/layouts/shortcodes/workflows/workflows.html
  website/site/package-lock.json
  website/site/package.json
  website/site/static/images/checked.png
  website/site/static/images/fire.png
  website/site/static/images/giphy.gif
  website/site/static/images/refresh.png
  website/site/static/images/spinner.png
Labels: ready-for-merge

#556 Fixing unit tests for updated SDK servers
  cdr_plugin_folder_to_folder/common_settings/Config.py
  tests/integration/configure/test_Configure_Env.py
  tests/integration/processing/test_File_Processing.py
Labels: ready-for-review

#542 Update auto_tagging.yml
  .github/workflows/auto_tagging.yml
Labels: ready-for-review

#543 Update auto_tagging.yml
  .github/workflows/auto_tagging.yml
Labels: ready-for-review

#557 Fix pre-processing incase of metadata.json is missing for a file
  cdr_plugin_folder_to_folder/metadata/Metadata.py
  tests/unit/metadata/test_Metadata.py
Labels: ready-for-merge

#505 Configure_env test coverage improvements - issue 504
  cdr_plugin_folder_to_folder/configure/Configure_Env.py
  tests/unit/configure/test_Configure_Env_core.py
Labels: ready-for-review

#558 Develop copy
  cdr_plugin_folder_to_folder/metadata/Metadata.py
  tests/unit/metadata/test_Metadata.py
Labels: ready-for-review
