Repository filetrust/cdr-plugin-folder-to-folder, pull requests merged in 2021-07, with the labels that each got.

#564 Revert "Develop copy"
  cdr_plugin_folder_to_folder/metadata/Metadata.py
  tests/unit/metadata/test_Metadata.py
Labels: ready-for-review

#561 Update .env.sample to reflect proper value of root_folder
  .env.sample
  cdr_plugin_folder_to_folder/Dockerfile
Labels: ready-for-merge

#563 Merging develop branch to my PR branch
  .env.sample
  .github/workflows/auto_tagging.yml
  cdr_plugin_folder_to_folder/Dockerfile
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/configure/Configure_Env.py
  cdr_plugin_folder_to_folder/metadata/Metadata.py
  tests/integration/configure/test_Configure_Env.py
  tests/integration/processing/test_File_Processing.py
  tests/unit/configure/test_Configure_Env_core.py
  tests/unit/metadata/test_Metadata.py
Labels: UI, ready-for-review

#554 [new UI] Added option to remove IP/PORT, set default port to 80 and fixed few minor UI issues
  website/site/assets/js/components/EditableTable/EditableTable.jsx
  website/site/assets/js/services/Utils.jsx
  website/site/assets/js/style.css
  website/site/assets/js/workflows/Configuration/Components/CloudSDK.jsx
  website/site/assets/js/workflows/Configuration/Components/Scenerios.jsx
Labels: Needs fix, UI

#568 few documentation fixes
  website/content/docs/0_Introduction.md
  website/content/docs/1_How_to_deploy_CDR_Plugin_AWS.md
  website/content/docs/2_How_to_deploy_CDR_Plugin_ESXI.md
  website/content/docs/3_End_to_end_workflow_AWS.md
  website/content/docs/4_End_to_end_workflow_ESXI.md
  website/content/docs/5_FAQ.md
  website/content/docs/6_How_to_start.md
  website/content/docs/7_Additional_workflows.md
Labels: ready-for-review

#569 Merge into main for release v0.14.0 (from v0.13.5)
  .env.sample
  cdr_plugin_folder_to_folder/Dockerfile
  cdr_plugin_folder_to_folder/configure/Configure_Env.py
  tests/unit/configure/test_Configure_Env_core.py
  website/content/docs/0_Introduction.md
  website/content/docs/1_How_to_deploy_CDR_Plugin_AWS.md
  website/content/docs/2_How_to_deploy_CDR_Plugin_ESXI.md
  website/content/docs/3_End_to_end_workflow_AWS.md
  website/content/docs/4_End_to_end_workflow_ESXI.md
  website/content/docs/5_FAQ.md
  website/content/docs/6_How_to_start.md
  website/content/docs/7_Additional_workflows.md
  website/site/assets/js/components/EditableTable/EditableTable.jsx
  website/site/assets/js/services/Utils.jsx
  website/site/assets/js/style.css
  website/site/assets/js/workflows/Configuration/Components/CloudSDK.jsx
  website/site/assets/js/workflows/Configuration/Components/Scenerios.jsx
Labels: P1, ready-for-review

#567 Update setup.sh
  infra/packer/setup/setup.sh
Labels: P1, ready-for-merge, ready-for-review

#573 Implementation of Kibana dashboards autoload - issue 33
  cdr_plugin_folder_to_folder/api/Server.py
  cdr_plugin_folder_to_folder/utils/_to_refactor/For_OSBot_Elastic/Dashboard_Manager.py
  tests/integration/elastic/test_Dashboard.py
  tests/integration/elastic/test_Dashboard_Manager.py
Labels: ready-for-review

#594 Properly handle bad SDK responses
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/processing/File_Processing.py
  tests/integration/processing/test_File_Processing.py
Labels: ready-for-review

#600 Get latest version of test_data when building an AMI image
  infra/packer/setup/setup.sh
Labels: ready-for-merge, ready-for-review

#610 Removed verify=False in line 162
  cdr_plugin_folder_to_folder/configure/Configure_Env.py
Labels: P1, ready-for-review

#614 Revert "Removed verify=False in line 162"
  cdr_plugin_folder_to_folder/configure/Configure_Env.py
Labels: P1, ready-for-review

#627 Release 15 sonar cloud issue 620
  tests/integration/elastic/test_Dashboard_Manager.py
Labels: ready-for-review

#612 Add cifs-utils to f2f plugin
  cdr_plugin_folder_to_folder/Dockerfile
Labels: P1, ready-for-review

#635 Updated Annotation
  kubernetes/helm/chart/templates/deployment.yaml
Labels: P1, ready-for-merge, ready-for-review

#634 Set image pull policy to Always
  kubernetes/helm/chart/values.yaml
Labels: P1, ready-for-merge, ready-for-review

#633 Updated Security Context
  kubernetes/helm/chart/templates/deployment.yaml
Labels: ready-for-merge, ready-for-review

#602 Corrected utilization of file utils
  cdr_plugin_folder_to_folder/common_settings/Config.py
  cdr_plugin_folder_to_folder/pre_processing/utils/file_service.py
  cdr_plugin_folder_to_folder/processing/File_Processing.py
  cdr_plugin_folder_to_folder/storage/Storage.py
  cdr_plugin_folder_to_folder/utils/file_utils.py
  tests/unit/pre_processing/utils/test_File_service.py
  tests/unit/utils/test_File_utils.py
  tests/unit/utils/test_files/easure
  tests/unit/utils/test_files/leasure
  tests/unit/utils/test_files/pleasure
Labels: ready-for-review
